### ISSUE TITLE
Allow camelCase for proxy to reflect dashes in tag name

### ISSUE THREAD

**Issue by quirm** [KoryNunn/crel#27]
Proxy mechanism is very convenient but I did not find a way to create tags with a dash, e.g. `<my-table></my-table>`. It would be convenient to use camelCase (as seen in css-loader) to proxy crel using `crelProxy.myTable()` over `crelProxy['my-table']`.

I could make a PR but somehow my editor (atom/vscode) changes white spaces and the whole file is marked as a change:
https://github.com/quirm/crel/commit/acb0c89b5660498d8b0f330331be47890dcab94d (a change https://github.com/quirm/crel/blob/master/crel.js#L159-L164)

**Comment by KoryNunn** [comment]
I'm guessing it's just line endings, check if you've got your editor set to lf or cr/lf, i don't know what this repo is but it'll likely be the opposite to what you've got :)

Change seems reasonable, but I'm generally not a fan of X becomes Y implicitly. I wonder if there's a clean way to do this with an initialization step..

**Comment by KoryNunn** [comment]
I'll pull your changes and see what I can do, you don't want to miss out on any internet points :)

**Comment by KoryNunn** [comment]
How's this look to you? https://github.com/KoryNunn/crel/pull/28

**Comment by quirm** [comment]
Using a factory function is not that convenient for ES6 imports with babel. If there are multiple files with imports like this:
```import { proxy as crel } from 'crel';```

Then, it can be used immediatelly. In case of a factory function, I would need to create crel proxy in every file or wrap it into my util function. My intention was to avoid wrapping the package and use it directly from the module.

**Comment by KoryNunn** [comment]
I'm not sure how to respond to this issue tonight without being unhelpful. Let me sleep on it.

**Comment by KoryNunn** [comment]
I don't want to make an arbitrary decision that involves implicit behavior.

Options:

1. Just don't use imports for crel, since it provides no benefit and hinders useful architectural patterns like state encapsulation.

2. Set up crel in your project, and symlink your root dir, so that it is easy to use:

package.json:
```
    ....
    "linkRoot": "ln -s ../ ./node_modules/^",
    "postInstall": "npm run-script linkRoot"
```
*.js:

```javascript
import * as crel from '^/crel';
```

3. Create myCoolCrel package on npm that just inits crel's proxy with your choice of key magic.

4. I've still not slept on it so maybe I'll have an answer you'll like in the morning.

I'd like to be clear that this is not arbitrary stubbornness on my behalf, and I really would like to help you out, but having to design around poor decisions being baked into JavaScript really grinds with me.

**Comment by KoryNunn** [comment]
FYI I have no idea if the `import * as crel from '^/crel'` syntax will work since it's a horrible syntax that adds no clarity and in fact generally obscures how the module system works. YMMV.

**Comment by quirm** [comment]
Thank you for the detailed info @KoryNunn .

**Comment by KoryNunn** [comment]
Sorry this didn't end up being very helpful for you.

I think I'll still end up using this change, as it also removes setup that currently happens in crel regardless of whether you use .proxy or not.

I'd personally recommend you try the symlink approach, i generally use it to symlink the root of a project to `^`, to avoid annoying paths like `../../../myModule`, and instead do `^/myModule`
